# Use root/example as user/password credentials
version: "3.1"

services:
  creatures_db:
    image: postgres
    restart: no
    ports:
      - 5678:5432
    environment:
      POSTGRES_PASSWORD: creatures
      POSTGRES_DB: creatures
      POSTGRES_USER: creatures

  adminer:
    image: adminer
    restart: no
    ports:
      - 7890:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql