# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - ./fs:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 12345678
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
