// <auto-generated />
using System;
using GameDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameDatabase.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20220829144400_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreatureWars.Class.AbilityPrototype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreaturePrototypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int[]>("PossibleTargets")
                        .HasColumnType("integer[]");

                    b.Property<string>("ProgramName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreaturePrototypeId");

                    b.ToTable("AbilityPrototypes");
                });

            modelBuilder.Entity("CreatureWars.Class.Attributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Dex")
                        .HasColumnType("integer");

                    b.Property<int>("End")
                        .HasColumnType("integer");

                    b.Property<int>("Int")
                        .HasColumnType("integer");

                    b.Property<int>("Str")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("CreatureWars.Class.CreaturePrototype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttributesId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProgramName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttributesId");

                    b.ToTable("CreaturePrototypes");
                });

            modelBuilder.Entity("CreatureWars.Class.ItemPrototype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttributesId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreaturePrototypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProgramName")
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttributesId");

                    b.HasIndex("CreaturePrototypeId");

                    b.ToTable("ItemPrototypes");
                });

            modelBuilder.Entity("CreatureWars.Class.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreaturePrototypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("MaxOnCharacter")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProgramName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreaturePrototypeId");

                    b.ToTable("ItemType");
                });

            modelBuilder.Entity("CreatureWars.Class.ModifierPrototype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbilityPrototypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreaturePrototypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("Heal")
                        .HasColumnType("integer");

                    b.Property<int?>("ItemPrototypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int[]>("PossibleTargets")
                        .HasColumnType("integer[]");

                    b.Property<string>("ProgramName")
                        .HasColumnType("text");

                    b.Property<double>("Tick")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AbilityPrototypeId");

                    b.HasIndex("CreaturePrototypeId");

                    b.HasIndex("ItemPrototypeId");

                    b.ToTable("ModifierPrototypes");
                });

            modelBuilder.Entity("CreatureWars.Class.AbilityPrototype", b =>
                {
                    b.HasOne("CreatureWars.Class.CreaturePrototype", null)
                        .WithMany("Abilities")
                        .HasForeignKey("CreaturePrototypeId");
                });

            modelBuilder.Entity("CreatureWars.Class.CreaturePrototype", b =>
                {
                    b.HasOne("CreatureWars.Class.Attributes", "Attributes")
                        .WithMany()
                        .HasForeignKey("AttributesId");

                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("CreatureWars.Class.ItemPrototype", b =>
                {
                    b.HasOne("CreatureWars.Class.Attributes", "Attributes")
                        .WithMany()
                        .HasForeignKey("AttributesId");

                    b.HasOne("CreatureWars.Class.CreaturePrototype", null)
                        .WithMany("Items")
                        .HasForeignKey("CreaturePrototypeId");

                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("CreatureWars.Class.ItemType", b =>
                {
                    b.HasOne("CreatureWars.Class.CreaturePrototype", null)
                        .WithMany("ItemTypes")
                        .HasForeignKey("CreaturePrototypeId");
                });

            modelBuilder.Entity("CreatureWars.Class.ModifierPrototype", b =>
                {
                    b.HasOne("CreatureWars.Class.AbilityPrototype", null)
                        .WithMany("ModifierPrototypes")
                        .HasForeignKey("AbilityPrototypeId");

                    b.HasOne("CreatureWars.Class.CreaturePrototype", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("CreaturePrototypeId");

                    b.HasOne("CreatureWars.Class.ItemPrototype", null)
                        .WithMany("ModifierPrototypes")
                        .HasForeignKey("ItemPrototypeId");
                });

            modelBuilder.Entity("CreatureWars.Class.AbilityPrototype", b =>
                {
                    b.Navigation("ModifierPrototypes");
                });

            modelBuilder.Entity("CreatureWars.Class.CreaturePrototype", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("ItemTypes");

                    b.Navigation("Items");

                    b.Navigation("Modifiers");
                });

            modelBuilder.Entity("CreatureWars.Class.ItemPrototype", b =>
                {
                    b.Navigation("ModifierPrototypes");
                });
#pragma warning restore 612, 618
        }
    }
}
